# Numpy - Numerical Python

ARRAY

In [4]:
import pandas as pd
import numpy as np

In [2]:
l11 = [1,2,3,4]
type(l)

list

In [16]:
a1 = np.array(l)
a1

array([1, 2, 3, 4])

In [17]:
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1,2],[3,4]])
type(a2)

numpy.ndarray

In [19]:
a2

array([[1, 2],
       [3, 4]])

In [33]:
a3 = np.array([[[1,2,6],[4,5,6],[8,9,0]]])
a3

array([[[1, 2, 6],
        [4, 5, 6],
        [8, 9, 0]]])

In [34]:
a1.ndim

1

In [35]:
a2.ndim

2

In [36]:
a3.ndim

3

In [37]:
a4 = np.array([[1,2,6],[4,5,6])
a4

array([[1, 2, 6],
       [4, 5, 6],
       [8, 9, 0]])

In [38]:
a4.ndim

2

In [46]:
#combination of 2D making 3 D
a5 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])
a5

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [43]:
l2 = [1,2,3,4]
a6 = np.asarray(l2)#works same as array
a6

array([1, 2, 3, 4])

In [47]:
l3= np.matrix(l2)
l3

matrix([[1, 2, 3, 4]])

In [50]:
a7 = np.asanyarray(l3)#converts any element belonging to array class into array
a7

matrix([[1, 2, 3, 4]])

In [56]:
a8=[1,2,4,9]
a8

[1, 2, 4, 9]

In [57]:
a8[1] = 0
a8# so array is mutable

[1, 0, 4, 9]

In [58]:
a9 = np.copy(a8)# Its an example of shallow copy
a9

array([1, 0, 4, 9])

In [59]:
a8[2]=9
a8

[1, 0, 9, 9]

In [60]:
a9#later changes in a8 is not reflected in a9......its an example of deep copy

array([1, 0, 4, 9])

In [61]:
# from function is used to generate a dataset
np.fromfunction(lambda i,j : i==j , (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [ ]:
# above command has generated 2d array

In [63]:
np.random.rand(2,3)#generates random array

array([[0.96751747, 0.88828569, 0.93641076],
       [0.59216813, 0.52059862, 0.44975228]])

In [64]:
np.random.rand(2,3,2)#3d array, it will create 2 arrays of dimension 3*2

array([[[0.08208551, 0.5366238 ],
        [0.09859773, 0.3153142 ],
        [0.74367117, 0.47269302]],

       [[0.67585609, 0.61423639],
        [0.38898739, 0.13281298],
        [0.22277521, 0.90825821]]])

In [65]:
np.random.rand(2,3,4,2)#4d array......twice 3 arrays of dimension 4*2 is shown

array([[[[0.98138593, 0.24686501],
         [0.56935438, 0.26513734],
         [0.26987767, 0.14388916],
         [0.04161259, 0.83164984]],

        [[0.75668674, 0.03441905],
         [0.21374914, 0.05670736],
         [0.4242428 , 0.55471891],
         [0.14241   , 0.28808435]],

        [[0.34424753, 0.26778201],
         [0.60984306, 0.12019193],
         [0.24767445, 0.48501897],
         [0.45802989, 0.12971277]]],


       [[[0.9271093 , 0.45953624],
         [0.32113844, 0.25725901],
         [0.88844828, 0.69857518],
         [0.13650036, 0.08338788]],

        [[0.38833474, 0.48046444],
         [0.1661328 , 0.90604109],
         [0.23254939, 0.46854884],
         [0.42087834, 0.42996745]],

        [[0.08298389, 0.29240835],
         [0.42255743, 0.87449383],
         [0.40304693, 0.48574986],
         [0.39157421, 0.06265637]]]])

In [ ]:
#randn generates data based on std normal distribution(mean = 0 and std dev = 1)

In [5]:
d = np.random.randn(3,4)
pd.DataFrame(d)

0         1         2         3
0 -0.272116 -0.100767  1.395869  1.504166
1  1.037528 -0.440557 -1.247386  1.094013
2 -0.525470 -1.056603  2.778712  0.685490

In [7]:
d1=np.random.randint(0,10,(4,4)) # this will generate a 4*4 matrix having interger numbers from 0 to 10
d1
#randint will generate integer data

array([[2, 8, 8, 0],
       [3, 8, 9, 7],
       [4, 4, 5, 6],
       [8, 7, 9, 3]])

In [8]:
d2=np.random.randint(0,10,(4,4,2)) # this will generate 4 arrays of dimension 4*2 matrix having integer numbers from 0 to 10
d2

array([[[3, 9],
        [5, 5],
        [3, 6],
        [7, 3]],

       [[7, 2],
        [3, 3],
        [9, 7],
        [6, 8]],

       [[3, 3],
        [8, 4],
        [2, 9],
        [8, 2]],

       [[3, 9],
        [3, 2],
        [7, 8],
        [3, 2]]])

In [ ]:
# Dataframe is bsically a 2D data 
# & to convert the multidimensional array to a dataframe... we should downconvert multidimensional array into 2d array
#in above case there are 32 elements........ 4*4*2 = 32
#it can be reshaped into a different dimension using reshape command

In [9]:
d2.reshape(16,2)

array([[3, 9],
       [5, 5],
       [3, 6],
       [7, 3],
       [7, 2],
       [3, 3],
       [9, 7],
       [6, 8],
       [3, 3],
       [8, 4],
       [2, 9],
       [8, 2],
       [3, 9],
       [3, 2],
       [7, 8],
       [3, 2]])

In [11]:
d2.reshape(8,4)

array([[3, 9, 5, 5],
       [3, 6, 7, 3],
       [7, 2, 3, 3],
       [9, 7, 6, 8],
       [3, 3, 8, 4],
       [2, 9, 8, 2],
       [3, 9, 3, 2],
       [7, 8, 3, 2]])

In [12]:
d3 = d2.reshape(8,4)
pd.DataFrame(d3)

0  1  2  3
0  3  9  5  5
1  3  6  7  3
2  7  2  3  3
3  9  7  6  8
4  3  3  8  4
5  2  9  8  2
6  3  9  3  2
7  7  8  3  2

In [17]:
# Same can be done through a different way............
# If we don't know number of elements init clearly and if we want an array of x rows ... write: dataframe_name(x,-1)
d4 = d2.reshape(8,-1)
pd.DataFrame(d4)

0  1  2  3
0  3  9  5  5
1  3  6  7  3
2  7  2  3  3
3  9  7  6  8
4  3  3  8  4
5  2  9  8  2
6  3  9  3  2
7  7  8  3  2

In [20]:
d4 = d2.reshape(4,-16)# any negative number can be used in place of -1
pd.DataFrame(d4)

0  1  2  3  4  5  6  7
0  3  9  5  5  3  6  7  3
1  7  2  3  3  9  7  6  8
2  3  3  8  4  2  9  8  2
3  3  9  3  2  7  8  3  2

In [22]:
d5 = d2.reshape(16,-167890066788)# any negative number can be used in place of -1
pd.DataFrame(d5)

0  1
0   3  9
1   5  5
2   3  6
3   7  3
4   7  2
5   3  3
6   9  7
7   6  8
8   3  3
9   8  4
10  2  9
11  8  2
12  3  9
13  3  2
14  7  8
15  3  2